# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomic_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='Family_Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='Genus_Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='Kingdom_Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='Order_Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='Phylum_Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='Subfamily_Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
